# Generated by Django 4.2.8 on 2024-01-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_photo_10_listing_photo_11_listing_photo_12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_choice',
            field=models.CharField(choices=[('house', 'house'), ('land', 'land'), ('apartment', 'apartment'), ('bungalow', 'bungalow'), ('duplex', 'duplex'), ('cottage', 'cottage')], default='house', max_length=20),
        ),
    ]
